version: '3'

services:
  mongodb: 
    container_name: netshoes-api-mongodb
    image: mongo
    ports:
      - "27017:27017"

  netshoes-api:
    container_name: netshoes-api
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    depends_on:
      - mongodb
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules

   